inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/environments/**
    - coverage/**/*
    - db/schema.rb
    - lib/tasks/*.rake
    - log/**/*
    - nginx/**/*
    - public/**/*
    - storage/**/*
    - swagger/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Bundler/OrderedGems:
  Enabled: false

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    attribute_macros:
      - attr
      - attr_accessor
      - attr_reader
      - attr_writer
      - attribute
      - serialize
      - encrypts
      - enum
    associations:
      - belongs_to
      - has_one
      - has_many
      - has_and_belongs_to_many
      - has_one_attached
      - has_many_attached
    scopes:
      - default_scope
      - scope
    validations:
      - validate
      - validates
      - validates_each
      - validates_with
    delegations:
      - delegate
    callbacks:
      - before_validation
      - after_validation
      - before_save
      - around_save
      - before_create
      - around_create
      - after_create
      - before_update
      - around_update
      - after_update
      - after_save
      - before_destroy
      - around_destroy
      - after_destroy
      - after_commit
      - after_rollback
      - after_initialize
      - after_find
      - after_touch
    protected_attribute_macros:
      - attr
      - attr_accessor
      - attr_reader
      - attr_writer
    private_attribute_macros:
      - attr
      - attr_accessor
      - attr_reader
      - attr_writer
  ExpectedOrder:
    - module_inclusion
    - constants
    - attribute_macros
    - associations
    - scopes
    - validations
    - delegations
    - callbacks
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/EmptyLineAfterMultilineCondition:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/**/*
    - spec/**/*
  Max: 50

Metrics/BlockNesting:
  Exclude:
    - spec/**/*'
  Max: 3

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Exclude:
    - db/migrate/*.rb
    - spec/**/*'
  Max: 45

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Exclude:
    - spec/**/*'
  Max: 250

Metrics/PerceivedComplexity:
  Max: 20

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolProc:
  AllowMethodsWithArguments: true

# rubocop-rails

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production

# rubocop-rspec

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
